### ISSUE TITLE
Game engine

### ISSUE THREAD

**Issue by tsjemo** [jazzsequence/CCG-Manager#9]
Requirements for additional features:
- cards should have properties like unique code, strength, speed,... (configurable) with its values
- users should be able to register cards by entering the unique code (system then knows which card they possess in their collection & links card and user)
- users should be able to challenge other users
- challenger & challenged users should indicate their used card for the 'upcoming battle'. Challenger indicates property and winner 'receives' both cards. If equal score, new property should be chosen for challenge. Cards may not be used for multiple battles at the same time.
- reporting (standings) based on user properties (age, location,...) and collection properties (number of cards, sum of values of property, number of registered cards, number of battles won,...)

The scope of the project is Belgium, Europe. Let's discuss your possiblities on budget and timing as I am really looking forward to realise this project.

**Comment by jazzsequence** [comment]
this isn't something that this WordPress plugin is going to do. closing as **wontfix**.
